context:
  version: "14.3.0"

package:
  name: eslint_d
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/eslint_d/-/eslint_d-${{ version }}.tgz
  sha256: f873d33ca7b7851704555a6453798163956a3f525a322d3caea8c16b294933c3

build:
  number: 0
  noarch: generic

requirements:
  build:
    - jq
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - eslint_d --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: Speed up eslint to accelerate your development workflow
  homepage: https://github.com/mantoni/eslint_d.js
  repository: https://github.com/mantoni/eslint_d.js

extra:
  recipe-maintainers:
    - danielnachun
